In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris

In [2]:
# Load Iris dataset
iris = load_iris()

# Create DataFrame
df = pd.DataFrame(
    iris.data,
    columns=iris.feature_names
)

# Rename columns
df.columns = [
    'sepal_length',
    'sepal_width',
    'petal_length',
    'petal_width'
]

# Add species column
df['species'] = pd.Categorical.from_codes(
    iris.target,
    iris.target_names
)

# Display first few rows
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [3]:
print("First 10 Rows:")
df.head(10)

First 10 Rows:

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa
7           5.0          3.4           1.5          0.2  setosa
8           4.4          2.9           1.4          0.2  setosa
9           4.9          3.1           1.5          0.1  setosa

In [4]:
print("Unique Species:")
print(df['species'].unique())

Unique Species:
['setosa', 'versicolor', 'virginica']
Categories (3, object): ['setosa', 'versicolor', 'virginica']

In [5]:
print("Flower Count by Species:")
species_count = df['species'].value_counts()

print(species_count)

Flower Count by Species:
species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [18]:
df['species'] = df['species'].astype(str)

avg_petal_length = df.groupby(
    'species'
)['petal_length'].mean()

print(avg_petal_length)

species
setosa        1.462
versicolor    4.260
virginica     5.552
Name: petal_length, dtype: float64

In [7]:
print("Flower with Maximum Sepal Length:")

max_sepal_flower = df.loc[
    df['sepal_length'].idxmax()
]

print(max_sepal_flower)

Flower with Maximum Sepal Length:
sepal_length          7.9
sepal_width           3.8
petal_length          6.4
petal_width           2.0
species         virginica
Name: 131, dtype: object

In [8]:
sorted_df = df.sort_values(
    by='petal_width',
    ascending=False
)

print("Sorted by Petal Width (Descending):")

sorted_df.head(10)

Sorted by Petal Width (Descending):

     sepal_length  sepal_width  petal_length  petal_width    species
100           6.3          3.3           6.0          2.5  virginica
109           7.2          3.6           6.1          2.5  virginica
144           6.7          3.3           5.7          2.5  virginica
114           5.8          2.8           5.1          2.4  virginica
140           6.7          3.1           5.6          2.4  virginica
136           6.3          3.4           5.6          2.4  virginica
148           6.2          3.4           5.4          2.3  virginica
115           6.4          3.2           5.3          2.3  virginica
145           6.7          3.0           5.2          2.3  virginica
143           6.8          3.2           5.9          2.3  virginica

In [9]:
filtered_df = df[
    df['petal_length'] > 5
]

print("Flowers with Petal Length > 5")

filtered_df.head()

Flowers with Petal Length > 5

     sepal_length  sepal_width  petal_length  petal_width     species
83            6.0          2.7           5.1          1.6  versicolor
100           6.3          3.3           6.0          2.5   virginica
101           5.8          2.7           5.1          1.9   virginica
102           7.1          3.0           5.9          2.1   virginica
103           6.3          2.9           5.6          1.8   virginica

In [10]:
df['total_size'] = (
    df['sepal_length']
    + df['petal_length']
)

print(df.head())

   sepal_length  sepal_width  petal_length  petal_width species  total_size
0           5.1          3.5           1.4          0.2  setosa         6.5
1           4.9          3.0           1.4          0.2  setosa         6.3
2           4.7          3.2           1.3          0.2  setosa         6.0
3           4.6          3.1           1.5          0.2  setosa         6.1
4           5.0          3.6           1.4          0.2  setosa         6.4

In [11]:
filtered_df.to_csv(
    "filtered_iris.csv",
    index=False
)

print("Filtered data saved as filtered_iris.csv")

Filtered data saved as filtered_iris.csv

In [12]:
petal_array = df['petal_length'].to_numpy()

print("NumPy Array:")

print(petal_array)

NumPy Array:
[1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 1.5 1.6 1.4 1.1 1.2 1.5 1.3 1.4
 1.7 1.5 1.7 1.5 1.  1.7 1.9 1.6 1.6 1.5 1.4 1.6 1.6 1.5 1.5 1.4 1.5 1.2
 1.3 1.4 1.3 1.5 1.3 1.3 1.3 1.6 1.9 1.4 1.6 1.4 1.5 1.4 4.7 4.5 4.9 4.
 4.6 4.5 4.7 3.3 4.6 3.9 3.5 4.2 4.  4.7 3.6 4.4 4.5 4.1 4.5 3.9 4.8 4.
 4.9 4.7 4.3 4.4 4.8 5.  4.5 3.5 3.8 3.7 3.9 5.1 4.5 4.5 4.7 4.4 4.1 4.
 4.4 4.6 4.  3.3 4.2 4.2 4.2 4.3 3.  4.1 6.  5.1 5.9 5.6 5.8 6.6 4.5 6.3
 5.8 6.1 5.1 5.3 5.5 5.  5.1 5.3 5.5 6.7 6.9 5.  5.7 4.9 6.7 4.9 5.7 6.
 4.8 4.9 5.6 5.8 6.1 6.4 5.6 5.1 5.6 6.1 5.6 5.5 4.8 5.4 5.6 5.1 5.1 5.9
 5.7 5.2 5.  5.2 5.4 5.1]

In [13]:
mean_value = np.mean(petal_array)
median_value = np.median(petal_array)
std_value = np.std(petal_array)

print("Mean =", mean_value)
print("Median =", median_value)
print("Standard Deviation =", std_value)

Mean = 3.7580000000000005
Median = 4.35
Standard Deviation = 1.759404065775303

In [14]:
max_value = np.max(petal_array)
min_value = np.min(petal_array)

print("Maximum Petal Length =", max_value)
print("Minimum Petal Length =", min_value)

Maximum Petal Length = 6.9
Minimum Petal Length = 1.0

In [15]:
normalized_petal = (
    petal_array - np.min(petal_array)
) / (
    np.max(petal_array) - np.min(petal_array)
)

print("Normalized Petal Lengths:")

print(normalized_petal)

Normalized Petal Lengths:
[0.06779661 0.06779661 0.05084746 0.08474576 0.06779661 0.11864407
 0.06779661 0.08474576 0.06779661 0.08474576 0.08474576 0.10169492
 0.06779661 0.01694915 0.03389831 0.08474576 0.05084746 0.06779661
 0.11864407 0.08474576 0.11864407 0.08474576 0.         0.11864407
 0.15254237 0.10169492 0.10169492 0.08474576 0.06779661 0.10169492
 0.10169492 0.08474576 0.08474576 0.06779661 0.08474576 0.03389831
 0.05084746 0.06779661 0.05084746 0.08474576 0.05084746 0.05084746
 0.05084746 0.10169492 0.15254237 0.06779661 0.10169492 0.06779661
 0.08474576 0.06779661 0.62711864 0.59322034 0.66101695 0.50847458
 0.61016949 0.59322034 0.62711864 0.38983051 0.61016949 0.49152542
 0.42372881 0.54237288 0.50847458 0.62711864 0.44067797 0.57627119
 0.59322034 0.52542373 0.59322034 0.49152542 0.6440678  0.50847458
 0.66101695 0.62711864 0.55932203 0.57627119 0.6440678  0.6779661
 0.59322034 0.42372881 0.47457627 0.45762712 0.49152542 0.69491525
 0.59322034 0.59322034 0.62711864 0.57627119 0.52542373 0.50847458
 0.57627119 0.61016949 0.50847458 0.38983051 0.54237288 0.54237288
 0.54237288 0.55932203 0.33898305 0.52542373 0.84745763 0.69491525
 0.83050847 0.77966102 0.81355932 0.94915254 0.59322034 0.89830508
 0.81355932 0.86440678 0.69491525 0.72881356 0.76271186 0.6779661
 0.69491525 0.72881356 0.76271186 0.96610169 1.         0.6779661
 0.79661017 0.66101695 0.96610169 0.66101695 0.79661017 0.84745763
 0.6440678  0.66101695 0.77966102 0.81355932 0.86440678 0.91525424
 0.77966102 0.69491525 0.77966102 0.86440678 0.77966102 0.76271186
 0.6440678  0.74576271 0.77966102 0.69491525 0.69491525 0.83050847
 0.79661017 0.71186441 0.6779661  0.71186441 0.74576271 0.69491525]

In [16]:
print("First 10 Normalized Values:")

print(normalized_petal[:10])

First 10 Normalized Values:
[0.06779661 0.06779661 0.05084746 0.08474576 0.06779661 0.11864407
 0.06779661 0.08474576 0.06779661 0.08474576]

In [17]:
print("="*50)
print("IRIS DATASET ANALYSIS REPORT")
print("="*50)

print("Total Flowers :", len(df))
print("Species :", df['species'].nunique())

print("\nSpecies Count")
print(df['species'].value_counts())

print("\nMean Petal Length :", np.mean(petal_array))
print("Max Petal Length :", np.max(petal_array))
print("Min Petal Length :", np.min(petal_array))

print("\nAnalysis Completed Successfully")
print("="*50)

==================================================
IRIS DATASET ANALYSIS REPORT
==================================================
Total Flowers : 150
Species : 3

Species Count
species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

Mean Petal Length : 3.7580000000000005
Max Petal Length : 6.9
Min Petal Length : 1.0

Analysis Completed Successfully
==================================================